### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by fedeadolfi** [MSzturc/obsidian-advanced-slides#1]
This looks great! Could you update the readme with instructions for manual installation? (I gather it's not available as a community plugin)

**Comment by fedeadolfi** [comment]
I followed the instructions [here](https://forum.obsidian.md/t/advanced-slides-create-markdown-based-reveal-js-presentations-in-obsidian/28243) and the plugin can be activated succesfully.

**Comment by MSzturc** [comment]
An alternative way would be using BRAT for installation. Advanced Slides is compatible to BRAT since 0.10.0.
A [pull request](https://github.com/obsidianmd/obsidian-releases/pull/682) for adding it into community plugins has been made, but until now not accepted.
