### ISSUE TITLE
Images with ()s in filename do not appear.

### ISSUE THREAD

**Issue by TimothyGutierrez** [MSzturc/obsidian-advanced-slides#100]
There is still one more issue of image files not appearing in the slide preview (or slide) in browser. I have been making a series of screenshots to embed in a presentation.

When I looked closely at the image, the images with (parentheses) did not display. When I removed the (), the image displayed as expected.

Not sure what to make of it.

**Comment by MSzturc** [comment]
Ohhh yeah.. nice find, the paths of image should be properly encoded too.. will fix this one with next version
