### ISSUE TITLE
As soon as I add a 'note:' to my slide, the template is no longer applied

### ISSUE THREAD

**Issue by pprazzi** [MSzturc/obsidian-advanced-slides#102]
I'm using a template for my slides 

`<!-- slide template="[[tpl-footer]]" -->`

It only contains an image 

```
<% content %>
<grid drag="100 5" drop="bottom" align="left" >
![[1314_logo.png]]
</grid>
```

It works fine, except when I add a `note:` to my slide, then it's gone

**Comment by MSzturc** [comment]
Yeah there is a gap in the workflow i've implemented. I will change this behavior with 1.15.

**Comment by MSzturc** [comment]
please retest

**Comment by pprazzi** [comment]
Thanks, that did the trick!
