### ISSUE TITLE
Change line wouldn't need extra empty line in editor would be better.

### ISSUE THREAD

**Issue by jiewangjs** [MSzturc/obsidian-advanced-slides#103]
Hi, thanks for such a nice product. 
As the title suggests, if not to change the current setting totally, adding a option may be a practial alternative. 
P.S. how is the difficulty adding a vertical preview layout ? For long slides, vertical scrolling similar to a long slide-page sized document would be more friendly.

**Comment by MSzturc** [comment]
will be fixed in next version
