### ISSUE TITLE
When embed markdown using #heading, and in that embeded markdown include some link to block like [[myfile#^5f4d3]], The link to block can't be recognized

### ISSUE THREAD

**Issue by ruanwz** [MSzturc/obsidian-advanced-slides#104]
When embed markdown using #heading, and in that embeded markdown, there is a link to block like [[myfile#^5f4d3]], the link to block can't be recognized.

For example:
```
in myslide.md:
![[myfile#heading]]

in myfile.md:
# heading
[[anotherfile#^56789|show this text]]

when view myslide.md in normal reading mode, it shows:
heading
show this text

but when view myslide.md using advanced slides, it shows:
heading
[[anotherfile#
```

This type of links to block is very useful for pdf annotations. Could you please see if it can also work in advanced slides? Thanks!

**Comment by zhao414** [comment]
+1 request for this feature. 

Embed the entire section from a note is one of the easiest way to make a quick presentation.

The output effect can refer the one of the built-in presentation function.

**Comment by MSzturc** [comment]
will be fixed with next release
