### ISSUE TITLE
Unexcepted white block when printing to pdf document. 

### ISSUE THREAD

**Issue by joezhouchenye** [MSzturc/obsidian-advanced-slides#105]
There are white blocks shown starting from the second slide and I have to manually edit the pdf result to remove them.

This is the image of print-pdf page, which looks good.

![image](https://user-images.githubusercontent.com/59191277/179435874-7a13de91-9fad-4278-812c-2bc8d2f374fa.png)

And this is the error looking of pdf result.

![image](https://user-images.githubusercontent.com/59191277/179435945-b8d0e402-3d87-44cc-a386-e0bb9d420d56.png)

As you can see, there is a black line rounded white rectangular.

**Comment by joezhouchenye** [comment]
It seems a browser issue. The print results of Microsoft Edge on my two computers both have the issue mentioned above. Switch to Google Chrome and there is no such problem.

![image](https://user-images.githubusercontent.com/59191277/179469560-dcd3596d-ebfc-4a67-b965-01725e4fd46a.png)

**Comment by joezhouchenye** [comment]
So can you please add a direct "export to PDF" feature to this plugin?

**Comment by MSzturc** [comment]
PDF Rendering of html files is tough. Please use Chrome in the future
