### ISSUE TITLE
Support embedding local media files outside an Obsidian vault

### ISSUE THREAD

**Issue by YIRU69** [MSzturc/obsidian-advanced-slides#106]
It would be great if one can embed media files like audio and videos outside the Obsidian vault. https://github.com/MSzturc/obsidian-advanced-slides/issues/7

**Comment by YIRU69** [comment]
I wish it can suppose embedding media in obsidian. By the way, could you support some way to achieve it?
Or how I display none for special text like: ![[xxx.mp3]]

**Comment by YIRU69** [comment]
![image](https://user-images.githubusercontent.com/48148292/179675511-1599cd26-4d13-4edf-8306-8a4f2f031c1e.png)
Above the image. 
1 is work at the plugin. 2 is not work. 
I mean, could let 2 work on the obsidian.

**Comment by MSzturc** [comment]
Had a look at this feature, it's not possible to use the second syntax since obsidian doesnt know locations outside of the vault
