### ISSUE TITLE
BUG: Display error 

### ISSUE THREAD

**Issue by YIRU69** [MSzturc/obsidian-advanced-slides#107]
```markdown
[[🅰Word-transient|Transient]] investors, who demand high quarterly profits from companies, can [[🅰Word-hinder|hinder]] a firm's efforts to invest in long-term research or to build up customer loyalty. This has been [[🅰Word-dub|dubbed]] "quarterly capitalism".
```
Above the text display error on the advanced sildes preview.
![image](https://user-images.githubusercontent.com/48148292/179680699-124d1276-a53a-4329-8007-ee5bb76782f1.png)

**Comment by YIRU69** [comment]
[[Word-transient|Transient]] is not ![[Word-transient|Transient]].
It not work that [[Word-transient|Transient]] on the start.
I mean the `Transient investors, who demand high quarterly profits from companies, can [[🅰Word-hinder|hinder]] a firm's efforts to invest in long-term research or to build up customer loyalty. This has been [[🅰Word-dub|dubbed]] "quarterly capitalism".` worked.

**Comment by MSzturc** [comment]
Im not able to reproduced this behavior. Please attach a zipped vault for me that reproduces this problem.

**Comment by YIRU69** [comment]
@MSzturc

**Comment by YIRU69** [comment]
[demo.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/9239073/demo.zip)

**Comment by MSzturc** [comment]
I cant open the zip file, it saids that the file is corrupt

**Comment by MSzturc** [comment]
fixed with next release
