### ISSUE TITLE
Hide a slide

### ISSUE THREAD

**Issue by ll7** [MSzturc/obsidian-advanced-slides#109]
Hello, I was wondering if it is possible to hide a slide as backup slide? I wasn't able to find this feature.

**Comment by ll7** [comment]
I wasn't able to implement this example: https://revealjs.com/slide-visibility/

**Comment by MSzturc** [comment]
You could annotate the slide with the following annotation:

```
<!-- slide data-visibility="hidden" `-->`
```

to hide the slide in the presentation
