### ISSUE TITLE
Split Component doesn't work for me

### ISSUE THREAD

**Issue by Liong1976** [MSzturc/obsidian-advanced-slides#11]
The instructions in this [link](https://mszturc.github.io/obsidian-advanced-slides/layout/split/) do not work for me. 

Here are the result of those codes:

![image](https://user-images.githubusercontent.com/88898230/146627736-f89cf31c-f594-46d5-b544-2bf117b3e2a2.png)
![image](https://user-images.githubusercontent.com/88898230/146627738-9d2da3c3-bdd8-478b-a0cc-1d5018d83c31.png)
![image](https://user-images.githubusercontent.com/88898230/146627741-3e5e00d8-549b-4a70-8eb5-b944bedd1ec3.png)
![image](https://user-images.githubusercontent.com/88898230/146627746-7ae318c8-5063-4ae7-b5f0-0547c5b5bbce.png)
![image](https://user-images.githubusercontent.com/88898230/146627749-3770bf0e-2ed5-4d78-8320-4842f59e60fc.png)

**Comment by MSzturc** [comment]
may i ask you to retest with 0.17.0?

**Comment by Liong1976** [comment]
It is working with v. 0.17.0, thanks!

**Comment by gmkado** [comment]
@MSzturc I am having this issue, on 0.17.8.  Does a setting need to be enabled to use the `<split>` tag?
