### ISSUE TITLE
Showing Metadata Value in slide

### ISSUE THREAD

**Issue by SylvainGuieu** [MSzturc/obsidian-advanced-slides#111]
Hello, 

I have tried to show a value from metadata with DataView but it does not work : 
```
`= this.author`
```

I guess DataView is not yet supported. Is there any other ways to do that  ? 
Would be nice to have such feature and would be even greater if one can enter the metadata directive in slide template.

**Comment by MSzturc** [comment]
This wound be possible for a long time since the process engine is completely separated from the obsidian runtime and therefore there is no way to integrate with plugins like dataview

**Comment by SylvainGuieu** [comment]
Can’t it be possible to add this feature within advanced slide engine ? 
possibility to replace a metadata pointer to its value.

**Comment by SylvainGuieu** [comment]
Hello I found an alternative to what I want to do. Which is not to difficult. 
I have a several  templates, each contains this :: 

```
<%? lfoot %><!-- element class="lfoot" -->
</grid>
<grid drag="50 5" drop="50 -5" align="bottomright" class="rfoot-grid">
<%? rfoot %><!-- element class="rfoot" -->
</grid>
```

Which defines 2 footer for my slide, on the right and left.

On my presentation markdown page I have this : 

```
<style>
.lfoot:after {
  content: "Proposal Meeting   2022-08-24";
}
.rfoot:after {
  content: "My Name";
}
</style>
```

This will add the content on each slides.  Surprisingly I need to add an empty `::: rfoot` block for the background content to appear but not for the `::: lfoot` (it does appear anyway). Probably a ccs trick I do not understand.
