### ISSUE TITLE
Scale one slide to make the content fit

### ISSUE THREAD

**Issue by Hubro** [MSzturc/obsidian-advanced-slides#112]
Some times I want to have more content on a specific slide, for example code snippets. These code snippets often don't fit on a slide, instead clipping outside the bottom.

Is there a way to change the "scale" of one specific slide, so everything appears smaller? Essentially zooming out, so everything fits on the slide?

**Comment by MSzturc** [comment]
You could annotate the element with:

\

**Comment by Hubro** [comment]
I don't want to modify one element though, but an entire slide.

After some more messing around I found that this works perfectly and does exactly what I want:

```html
<!-- slide style="font-size: 15pt" -->
```

**Comment by clementaudic** [comment]
The [Custom slides plugin](https://community.obsidian.md/plugins/custom-slides) has a great feature called "Auto-fit slides" for that.
