### ISSUE TITLE
Advanced Slides not opening Excalidraw Image

### ISSUE THREAD

**Issue by TimothyGutierrez** [MSzturc/obsidian-advanced-slides#115]
Likewise, having issues opening excalidraw image in advanced slides.
code matches https://mszturc.github.io/obsidian-advanced-slides/extend-syntax/excalidraw/

Output is as attached image.
<img width="612" alt="Screen Shot 2022-08-01 at 19 47 42" src="https://user-images.githubusercontent.com/90198967/182181958-4212134a-a108-4ded-9499-e4228ebaf897.png">

Obsidian Version 0.15.9
Advanced Slides Version 1.15.0

**Comment by MSzturc** [comment]
please try this tho options:
- ![[2021-10-24 14-25-12.excalidraw.md]]
- ![[2021-10-24 14-25-12.excalidraw]]

Does one of those work?

**Comment by TimothyGutierrez** [comment]
Both of these options are working now. I'm not sure what changed, but thank you.

**Comment by MSzturc** [comment]
In your example you specified the relative path to the vault. Currently, Advanced Slides does not support file paths, only files themselves. I'll see if I can adjust this in the next version

**Comment by DLGMosheSteinberg** [comment]
@MSzturc - I'm getting the same issue as Timothy. I have not specified the relative path in the markdown, but the slides are showing ![[relative path]] instead of the excalidraw drawing
