### ISSUE TITLE
Really weird behavior with global background and empty slide at the end of the markdown

### ISSUE THREAD

**Issue by pbacellar** [MSzturc/obsidian-advanced-slides#118]
Hello, I came a across a really weird behavior when using global background and leaving an empty slide at then end of the markdown, i.e., a lone `---`. It's nothing major, just quite odd because It only happens when there is exactly one line break after the `---`, no more no less.

See this minimal example:

```
---
bg: "#f7c9fb"
---

Hello

---

```

Result:
![image](https://user-images.githubusercontent.com/20764763/183274983-bd16c8c2-12b4-49d1-8b8c-c35ab926e8ad.png)

It messes up  the text and it is not possible to change slides. Sometimes it crashes completely, having to restart the preview. Other times, simply fixing the markdown suffices.

**Comment by MSzturc** [comment]
will be fixed with next release
