### ISSUE TITLE
.excalidraw.png files when Excalidraw enabled not showing in slide preview

### ISSUE THREAD

**Issue by MosheSteinberg** [MSzturc/obsidian-advanced-slides#119]
I have enabled 1.15.0 of this plugin and 1.7.11 of Excalidraw. When I link to this file e.g. ![[thing.excalidraw.png]], it does not render in a slideshow and gives me this in the console:
![image](https://user-images.githubusercontent.com/46159405/184225621-1ab34acd-3bf1-4eed-aa2f-79df3fb9972b.png)

**Comment by MSzturc** [comment]
try without png extension e.g. ![[thing.excalidraw]]

**Comment by fnumatic** [comment]
In Excalidraw | Export Settings
[x] keep .svg ... in sync
[x] auto export SVG

use normal embedded link syntax without additional image suffix:
![[foo.excalidraw]]

**Comment by hrenaud** [comment]
Hello, 
I would just like to add that the configuration proposed by @fnumatic  works very well, however, if we configure Excalidraw so that it exports the dark version and the light version, it does not work anymore.

Thanks for this plugin 👌
