### ISSUE TITLE
Feature Request: A Command for Show Slide Preview

### ISSUE THREAD

**Issue by Liong1976** [MSzturc/obsidian-advanced-slides#12]
Thanks a lot for making this plugin.

Could you make a command for Show Slide Preview to show the slide preview using a hotkey instead of clicking an icon on the ribbon since I usually hide the left ribbon? Many thanks for considering my request.

**Comment by MSzturc** [comment]
Will be available with 0.17.0

**Comment by Liong1976** [comment]
Thanks a lot @MSzturc!
