### ISSUE TITLE
Show Slide Preview doesn't load on startup

### ISSUE THREAD

**Issue by axelson** [MSzturc/obsidian-advanced-slides#120]
If the Slide Preview was open when Obsidian was closed then after Obsidian is reopened the Advanced Slides Slide Preview pane remains blank and never updates. After toggling the slide preview on and off again it works.

Note: This also affects loading a workspace that includes an Advanced Slides Slide Preview pane.

**Comment by MSzturc** [comment]
will be fixed with next version
