### ISSUE TITLE
nested block does not  work well with templates

### ISSUE THREAD

**Issue by SylvainGuieu** [MSzturc/obsidian-advanced-slides#123]
I have copied the block exemple from the documentation. One using a template and one without :

```md
no color

::: block <!-- element style="background-color: red;" -->

everything inside this block has red background color

::: block <!-- element style="background-color: blue;" -->

blue

::: 

red

:::
no color

---
<!-- slide template="[[stpl-void]]" -->

no color

::: block <!-- element style="background-color: red;" -->

everything inside this block has red background color

::: block <!-- element style="background-color: blue;" -->

blue

::: 

red

:::
no color
```

The `stpl-void` template contains only  `<% content %>` (for problem hunting  purpose).

It seems that some opening div blocks are missing when using the template, see the comparaison between both :

```html
<section  data-markdown><script type="text/template">

no color

<div class="block">

<!-- .element: style="background-color: red" -->

everything inside this block has red background color

<div class="block">

<!-- .element: style="background-color: blue" -->

blue

</div>



red

</div>


no color
</script></section><section  data-markdown><script type="text/template">

no color



blue

</div>



red

</div>


no color
</script></section>
```

**Comment by SylvainGuieu** [comment]
More exemple : 

```
<!-- slide template="[[stpl-void]]" -->

Outside a block

::: block 
A first block
:::

::: block
An second block
:::
```

Will output: 

![image](https://user-images.githubusercontent.com/14850878/186639886-0e7af44e-31bd-4734-81b8-168640033512.png)

The first block completely disappeared in the html :

```html
<section  data-markdown><script type="text/template">


Outside a block



<div class="block">

An second block
</div>

</script></section>
```

**Comment by SylvainGuieu** [comment]
Sorry, more on this : 

```md
<!-- slide template="[[stpl-void]]" -->

Outside a block

::: block 
A first block
:::

::: block 
A second block
:::

---


Outside a block

::: block 
A first block
:::

::: block 
A second block
:::
```

The first slide : 
![image](https://user-images.githubusercontent.com/14850878/186646588-10050929-356b-4946-b415-693d58d0ac57.png)
The Second : 
![image](https://user-images.githubusercontent.com/14850878/186646660-0c9f011e-97ad-45a3-8e7c-47fd598530f0.png)

However if I remove the space after  "::: block" it works in both cases. Seems that a trailing space (or anything else like `<`) after block has an effect only when using content inside a template.

**Comment by MSzturc** [comment]
will be fixed with next version
