### ISSUE TITLE
Problem to match two wiki links on the same line 

### ISSUE THREAD

**Issue by SylvainGuieu** [MSzturc/obsidian-advanced-slides#124]
In md:
```
[[logo1.png]]    [[logo2.png]] 
```

Will render in html 
```html 
logo1.png]]     [[logo2.png 
```

Equal when including images:
```
![[logo1.png]]    ![[logo2.png]] 
```
renders:
```html
<p style="line-height: 0" class="reset-paragraph image-paragraph"><img src="logo1.png]] ![[logo2.png" alt="" ></img></p>
```

Easy to workaround when you know .

**Comment by MSzturc** [comment]
will be fixed with next version

**Comment by SylvainGuieu** [comment]
Thanks .
Just tried. It worked for the reference link  ` transformImageReferenceString` 

 I guess   `transformImageString` and `obsidianImageRegex` needs also to be updated ? 
 
```
![[logo1.png]]    ![[logo2.png]] 
```
Still does not wok. 

Cheers and great work again.

**Comment by MSzturc** [comment]
Ahhh yeah, will fix it later, thx for your testing effort :-)

**Comment by MSzturc** [comment]
done
