### ISSUE TITLE
Block reference are shown in presentation

### ISSUE THREAD

**Issue by SylvainGuieu** [MSzturc/obsidian-advanced-slides#125]
Not a big deal,  for the record, block references appear in slides.

```
Block of  Text
^refblock
```

![image](https://user-images.githubusercontent.com/14850878/186846362-e2453456-33a8-43a7-86c4-8a1f930ccff7.png)

Found when trying to embed a note (containing block references).
Cheers.

**Comment by SylvainGuieu** [comment]
Also I encountered a problem when referencing a code block, the closing  `"```"` are missing. 

e.g. 
```
Somewhere 
```pyhton
for i in range(10):
	print(i)
\```
^codeexemple
```

somewhere else:

```

![[slide tutorial#^codeexemple]]

Problem
```

![image](https://user-images.githubusercontent.com/14850878/186857949-f4bfa9b3-fded-4672-b621-db7af4b93a2e.png)

Looking at html : 

```html
       <div class="slides"><section  data-markdown><script type="text/template">
```pyhton
for i in range(10):
	print(i)



Problem

</script></section></div>
```


Hope this helps.

**Comment by SylvainGuieu** [comment]
For the problem #2  :

Adding +1  to presolved.end.line   solve this specific problem. Do not know if they are side effects. 

```ts
	if (resolved && resolved.start && resolved.start.line != null) {
		if (resolved.end && resolved.end.line != null) {
			return this.substring(fileContent, resolved.start.line, resolved.start.col, resolved.end.line+1, resolved.end.col);
		} else {
			return this.substring(fileContent, resolved.start.line, resolved.start.col, -1, -1);
		}

	} else {
		return '![[' + relativeFilePath + '#' + header + ']]';
	}
```

**Comment by MSzturc** [comment]
will be fixed in next version
