### ISSUE TITLE
note internal reference does not work

### ISSUE THREAD

**Issue by SylvainGuieu** [MSzturc/obsidian-advanced-slides#126]
Hi again, 

Contrary to obsidian engine :

```
[[#^someref]]
```

Does not work. 

The function `parserFile` is receiving  '.md'  as relativeFilePath  

I can patch this by adding : 

```ts
parseFile(relativeFilePath: string, header: string) {
        
        if (relativeFilePath === '.md'){
           relativeFilePath = this.app.workspace.getActiveFile().name; 
        }
    .... etc ...
```

but I am guessing they are much better ways to do this.

**Comment by MSzturc** [comment]
Didnt know that obsidian supports refs without sourcefile. I will have a look at it

**Comment by MSzturc** [comment]
Since reveal.js does not have a blockref concept it's to much effort to implement this feature.
