### ISSUE TITLE
1.16.6 can't preview correctly, with a blank page.

### ISSUE THREAD

**Issue by curcurve** [MSzturc/obsidian-advanced-slides#127]
Problem as issue title. When changing to v1.16.5, everthing went Ok.

**Comment by MSzturc** [comment]
Im not able to reproduced this issue, do you have a sample for me?

**Comment by curcurve** [comment]
There is a test vault attached and with v1.16.6 which doesn't run on my environment. Wish it's helpful.


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "MSzturc/obsidian-advanced-slides"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Aug 27, 2022 05:17 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [MSzturc/obsidian-advanced-slides] 1.16.6 can't preview correctly, with a blank page. (Issue #127)





 
Im not able to reproduced this issue, do you have a sample for me?

**Comment by MSzturc** [comment]
The attachment was not provided by the Mail function, you have to upload it to github

**Comment by curcurve** [comment]
fine, then try this link. By the way, my obsisdian is of the newest version.
vault-for-ob_slides/test.zip at main · curcurve/vault-for-ob_slides (github.com)




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "MSzturc/obsidian-advanced-slides"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Aug 27, 2022 08:06 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [MSzturc/obsidian-advanced-slides] 1.16.6 can't preview correctly, with a blank page. (Issue #127)





 
The attachment was not provided by the Mail function, you have to upload it to github

**Comment by MSzturc** [comment]
Hmm i cant find an issue, the test file works for me as expected

**Comment by curcurve** [comment]
Strange, then I'll use last version. Really awesome work!




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "MSzturc/obsidian-advanced-slides"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Aug 27, 2022 08:57 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [MSzturc/obsidian-advanced-slides] 1.16.6 can't preview correctly, with a blank page. (Issue #127)





 
Hmm i cant find an issue, the test file works for me as expected
