### ISSUE TITLE
Error on Show Slide Preview

### ISSUE THREAD

**Issue by jomalla123** [MSzturc/obsidian-advanced-slides#130]
Hi,

I just installed the plugin via obsidian community, but when I click on "Show slide preview" I just get a blank pane. In the console the following error pops up:

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\Users\username\Obsidian Workspace\Vault\.obsidian\plugins\obsidian-advanced-slides\template\reveal.html'
```

Any idea why this might happen and how I could solve this issue?  As the features of the plugin seem awesome, I really would like to use the plugin :)

**Comment by MSzturc** [comment]
Have a look at #80 or #72 it seams to be an issue with your Internet connection. Advanced Slides downloads the reveal runtime on first start which did not happen in your case
