### ISSUE TITLE
Default templates

### ISSUE THREAD

**Issue by ebetica** [MSzturc/obsidian-advanced-slides#131]
I'm unsure if this is already implemented, but it would be nice to have a default template for the entire slide. I don't like having to preamble most of my slides with a template, when they're mostly the same.

**Comment by MSzturc** [comment]
No thats not possible right now. Im missing this feature too. Currently im very busy in my day job, but as soon as i get some spare time to work on it i will implement this feature

**Comment by fuzihaofzh** [comment]
Also looking forward to this feature. The default template looks bad and I found making a new one by myself a little bit challenge.

**Comment by MSzturc** [comment]
will be implemented with next version

**Comment by fuzihaofzh** [comment]
@MSzturc Thanks very much for your great work. May I know if there is any document we can refer for the update?

**Comment by MSzturc** [comment]
Yes there is:

https://mszturc.github.io/obsidian-advanced-slides/templates/#default-template

**Comment by fuzihaofzh** [comment]
Thanks for the great work. It helps a lot.
