### ISSUE TITLE
MathJax aligned environment breaks in templates

### ISSUE THREAD

**Issue by ebetica** [MSzturc/obsidian-advanced-slides#132]
**Describe the bug**
Here's an aligned environment, we expect the double backslash to add a new line (this equation has 2 lines)
```
$$
\begin{align}
A x^{5} &< x^{5} - 3x^{2} + 10 &< B x^{5} \\
A &< 1 - \frac{3}{x^{3}} + \frac{10}{x^5} &< B
\end{align}
$$
```

If we add any template to this slide, it appears that the double backslash will be interpreted as a single backslash, and the equation will only display 1 line (4 \ works).

```
<!-- slide template="[[ANY_TEMPLATE_SEEMS_TO_BREAK_IT_HERE]]" -->
$$
\begin{align}
A x^{5} &< x^{5} - 3x^{2} + 10 &< B x^{5} \\
A &< 1 - \frac{3}{x^{3}} + \frac{10}{x^5} &< B
\end{align}
$$
```

It's inconsistent, because without the template line, it'll display properly. I think Obsidian requires just 2 backslashes, not 4.

**Comment by MSzturc** [comment]
will be fixed in next release
