### ISSUE TITLE
gitGraph support in mermaid

### ISSUE THREAD

**Issue by marc-bouvier** [MSzturc/obsidian-advanced-slides#136]
Hi, keep up the good work, I use this plugin everyday, and it makes me really more productive.

**Problem**

I cannot use gitGraph diagrams in advanced slides.
But it is already available in obsidian and core slide plugin.

**Solution**

- Use a latest version of mermaidJs dependency (e.g. 9.1.7)
- I've proposed a [merge request](https://github.com/zjffun/reveal.js-mermaid-plugin/pull/1) to zjffun/reveal.js-mermaid-plugin which is the dependency used by this project to support mermaid.
- If the MR is accepted, obsidian-advanced-slide could upgrade yarn dependencies
  - "reveal.js-mermaid-plugin": "^0.0.2" -> "reveal.js-mermaid-plugin": "^0.0.3",
  
**Alternative**

- Use my own fork https://github.com/baldir-fr/reveal.js-mermaid-plugin
  - [packaged on github packages](https://github.com/baldir-fr/reveal.js-mermaid-plugin/pkgs/npm/reveal.js-mermaid-plugin)

**Comment by marc-bouvier** [comment]
Update: Pull request was accepted
https://github.com/zjffun/reveal.js-mermaid-plugin/pull/1

**Comment by MSzturc** [comment]
will be implemented in next version
