### ISSUE TITLE
Blank presentation display after export as HTML

### ISSUE THREAD

**Issue by kometenstaub** [MSzturc/obsidian-advanced-slides#143]
**Describe the bug**
When using the export as HTML option, the presentation disappears. The tab is still there, but it is empty.

However, I could not reproduce this with a simple presentation in the sandbox vault. 

Obsidian version: 0.16.5

**Samples to Reproduce**
Steps & Examples to reproduce the behavior:

1. Have slides
2. Use the Advanced Slides "Show Slides" feature
3. Export as HTML
4. The presentation disappears, the tab blanks out
5. When I reload manually with the action in the tab title bar, I get the following error

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/83140328/195521622-b38c3546-2b8e-4571-a07f-0feeb707d481.png">

<img width="952" alt="image" src="https://user-images.githubusercontent.com/83140328/195521812-33426ae5-a4e5-4a1a-bfcf-a0d9e086d76a.png">

The presentation is in the main window at that time.

**Expected behavior**
I'd expect it to still show the presentation after exporting it to HTML, no pop-out window is open.

As I could not reproduce this in the help vault, I hope that someone else has an idea where the issue might be.

**Comment by MSzturc** [comment]
That problem occurs because the current version of advanced slides is not compatible to 0.16 and later releases. 

I've described the reason why it's not compatible here:
https://github.com/MSzturc/obsidian-advanced-slides/issues/129

**Comment by kometenstaub** [comment]
Ah, sorry. I read that thread but thought it only affected theming.

**Comment by MSzturc** [comment]
will be fixed with 1.18

**Comment by kometenstaub** [comment]
Thank you
