### ISSUE TITLE
Slides in file name with spaces is not working

### ISSUE THREAD

**Issue by mkusz** [MSzturc/obsidian-advanced-slides#145]
**Describe the bug**
When file name contains spaces, advanced slides preview do not work.

**Samples to Reproduce**
1. Create new note with spaces in file name
2. Create simple slide
3. Open slide preview
4. Preview will be blank

**Expected behavior**
Slides preview works when spaces are in file name

**Comment by MSzturc** [comment]
nice find, will fix this issue with next version

**Comment by MSzturc** [comment]
Can you provide me a sample where this problem occurs? 
I've tried to reproduce it (on MacOS) and was not able to:


<img width="1156" alt="image" src="https://user-images.githubusercontent.com/4275753/195871230-685cd694-0c21-4139-9169-c525775207a0.png">

**Comment by mkusz** [comment]
![image](https://user-images.githubusercontent.com/9740637/196150338-50f57c19-42cc-4568-ac4c-a8efc7966f5e.png)

I also see some error in dev tools:

![image](https://user-images.githubusercontent.com/9740637/196150663-912d39cb-7058-448e-a936-8144e988e6c5.png)

No sure but maybe it's some sort of problem with other plugin interaction.

**Comment by mkusz** [comment]
@MSzturc was playing a bit with file names, and it seems that the space is not a problem. The problem is with `?` at the end of the file name. `?` is changed to `%3F` by obsidian (take a look at previous message console screenshot) but on MacOS (not sure about other systems) real file name contains `?` not `%3F`. It seems that the problem is with file name conversion not with spaces. Probably other chars could have the same problem. Hope it helps with fix creation.
PS. Should I rename issue title?

**Comment by MSzturc** [comment]
will be fixed with 1.19
