### ISSUE TITLE
Slide Preview and Slide View in Browser not working, after auto update of Obsidian to v1.0.0

### ISSUE THREAD

**Issue by krsnacaitanya** [MSzturc/obsidian-advanced-slides#146]
**Describe the bug**
I cannot open the Advanced slides preview or browser view anymore.

**Samples to Reproduce**
Open the file with notes, click on "show slide preview". An empty Tab opens but has no content. Show in Browser button opens a browser tab, but localhost:3000 is not working. (Yesterday before the update it worked fine)

**Expected behavior**
The selected note should appear in slide mode. The show in browser button opens the note in the browser.

**Comment by krsnacaitanya** [comment]
After disabling and enabling the plugin, it is working. But without option "show tab title bar" the slide preview buttons are not shown.

![image](https://user-images.githubusercontent.com/9249375/195791467-12089b5f-9443-432f-b873-e6ce8daeea8a.png)

**Comment by MSzturc** [comment]
Im not able to reproduce the behaviour you described, the update from 0.15.9/0.16.4 -> 1.0.0 on 3 devices of mine went without any issues. Were there any exceptions in the developer console?

**Comment by krsnacaitanya** [comment]
Hm, then it must have been something else. Sorry for false alert. You may close the issue then.

I didn't check the console.

**Comment by krsnacaitanya** [comment]
closed, not reproducable

**Comment by alltagsverstand** [comment]
I can confirm this issue on Ubuntu 20.04 (in case that matters...). After checking the console it seems there occurs an error when trying to load the chalkboard plugin. With the plugin disabled, everything is working as expected.

**Comment by MSzturc** [comment]
Interesting, Can you post a screenshot of this exception? Have only a Windows/Mac machine to test

**Comment by alltagsverstand** [comment]
![advsl](https://user-images.githubusercontent.com/14313301/196043715-aea24a25-ddbf-4706-a595-a65cff4ce540.jpg)

I just realized when posting this screenshot that there is a comma missing after "RevealPointer" - so I tried to activate the Chalkboard plugin and deactivate the pointer plugin instead - and it is working! Just not with both plugins activated...

**Comment by MSzturc** [comment]
Awww.. there was a merge error... will fix with next release
