### ISSUE TITLE
Frontmatter Tag for notes not recognized

### ISSUE THREAD

**Issue by dkgrieshammer** [MSzturc/obsidian-advanced-slides#157]
**Describe the bug**
Currently changing the note-tag in Frontmatter is not reflected / ignored 

**Samples to Reproduce**
1. Write Slide with note: this is a note
2. Set notesSeparator in Frontmatter to anything else, still only "note:" is recognized; e.g.:
```
---
notesSeparator: "^Whatever:"
---
```
3. save & preview; this is a note is hidden, changing the keyword to Whatever: is not recognized. Restarting Presentation etc. does not help. 

**Expected behavior**
- Frontmatter-Tag `notesSeparator`should be reflected, ideally this could be an option/input field in settings.

Note:
I tried to find it in code and fix it, seems I need some more time to understand the specific plugin architecture and obsidian plugins in general.

**Comment by MSzturc** [comment]
will be fixed with 1.19

**Comment by benjamin051000** [comment]
Still not working for me :(
