### ISSUE TITLE
Default font sizes are too big

### ISSUE THREAD

**Issue by ssarraju** [MSzturc/obsidian-advanced-slides#161]
**Describe the bug**
The font in the default presentation is too big. 
**Samples to Reproduce**
Install latest obsidian
Use Things theme
Create a sample note

`# Slide 1

* Point 1
	* Point 2
* Test
* Test
* 

---

# Slide 2.1

--

# Slide 2.2

—

—
`
Click on the advanced slides preview
**Expected behavior**

**Comment by ssarraju** [comment]
![Screen Shot 2022-11-01 at 3 33 29 PM](https://user-images.githubusercontent.com/391986/199354518-c085ad4a-6b9b-4ea2-a882-80b72079b1b8.png)

**Comment by MSzturc** [comment]
That's the normal behaviour of revealjs.
You have two options:

1. If you into css/html you could create your own theme that uses a smaller font size
2. You could increase the size of the canvas by setting width and height property in frontmatter (default is 960x700)
