### ISSUE TITLE
Drag px value not recognised

### ISSUE THREAD

**Issue by AdrianSimionov** [MSzturc/obsidian-advanced-slides#177]
**Describe the bug**
When specifying the drag values appended by px, as mentioned in the documentation, the px value is ignored and percentage is used instead.

**Samples to Reproduce**
```
<grid drag="50px 50px" drop="10px 10px" border="1px solid white">
A
</grid>
```

**Expected behavior**
The grid would have a size of 50px by 50px positioned 10px from the border.

**Comment by KarstenB** [comment]
How does this related to the obsidian advanced slides plugin? Grids are a feature of obsidian itself.

**Comment by bchmura** [comment]
I have the same issue.  as a new user, it drove me nuts trying to figure out what I was doing wrong : )

**Comment by AdrianSimionov** [comment]
I started adding CSS and it is working fine:

<grid style="top: 130px; left: 60px; height:830px; width:1800px; border: 1px solid red">

Until it gets fixed, this should be more than enough.

**Comment by MSzturc** [comment]
will be fixed with next release
