### ISSUE TITLE
Embedding a slide doesn't work with wikilink

### ISSUE THREAD

**Issue by psarras** [MSzturc/obsidian-advanced-slides#179]
**Describe the bug**
I tried the example shown in the documentation with an existing presentation in my vault. However I am getting `Parameters invalid: t.toLowerCase is not a function`. This is working if I provide the full path as a string.

i.e.

```slide
{
	slide: "path//to-my//presentation.md",
	page: 6
}
```

**Expected behavior**
To work with wikilinks

i.e.

```slide
{
	slide: [[presentation]],
	page: 6
}
```

**Comment by MSzturc** [comment]
This should be fixed with #197 please retest with 1.20
