### ISSUE TITLE
auto complete setting "only in Slide Preview" does not work

### ISSUE THREAD

**Issue by PaulAmosKreiner** [MSzturc/obsidian-advanced-slides#182]
**Describe the bug**
I have the auto complete setting set to "only in Slide Preview", yet that never actually worked for me. I have to quit Obsidian and start it up again to disable auto complete suggestions practically

**Samples to Reproduce**
Open the Slide Preview for any note. Close it again. Now auto complete is active in all notes until Obsidian is shut down completely.

**Expected behavior**
I expected auto complete to only be active when there is a Slide Preview open.

**Comment by MSzturc** [comment]
will be fixed with next version
