### ISSUE TITLE
Advertising policy requirement 

### ISSUE THREAD

**Issue by lishid** [MSzturc/obsidian-advanced-slides#183]
Hi there,

We've received reports from several concerned users that this plugin opens unsolicited popup modals for self-advertising.

I understand that funding is important for your plugin's continued development, but using popup modals to solicit sponsorship is a rather unpleasant experience for a large number of users, and does not mix well with the ethos of Obsidian.

To help with funding, we will be providing additional ways for plugins to request for donation and sponsorship in upcoming updates - stay tuned for that.

In the meantime, please come up with a different way to ask for funding, one which is more gentle, relates to your plugin's functionality, and in your plugin's own UI elements (such as the settings page, or in your plugin's custom views).

Read more about the advertisement policy here: https://github.com/obsidianmd/obsidian-releases#advertisement-policy

> In addition, advertisements must not show up spontaneously, such as in a pop-up modal, notice, etc. They must only be delivered in the plugin's own interfaces (for example: custom views, settings tab), or be triggered by a deliberate user action (for example: clicking a button that says "learn more").

**Comment by MSzturc** [comment]
As described in this [Post](https://forum.obsidian.md/t/advanced-slides-create-markdown-based-reveal-js-presentations-in-obsidian/28243/203) i've changed the behaviour of the 'Letter from Development'. It will now show once a month, when the user opens a slide.

**Comment by lishid** [comment]
Yay, happy to have you back once the release is made!

**Comment by MSzturc** [comment]
@lishid Advanced Slides 1.20 is release

**Comment by lishid** [comment]
I've re-listed the plugin here: https://github.com/obsidianmd/obsidian-releases/commit/236e6578b41bbd81f015ae8294f32d9e3adb7b6e
