### ISSUE TITLE
`+` character in a fragmented list does not work correctly

### ISSUE THREAD

**Issue by devkev** [MSzturc/obsidian-advanced-slides#188]
**Describe the bug**
If I have a fragmented list entry where the text of the line contains a `+` character, then the list item does not render correctly.

**Samples to Reproduce**

In all of the below cases, the list entries render correctly if the `+` is changed to `-`.

Example 1:
```
- foo
+ a + b
```
renders as:
```
- foo
- a - b
```

Example 2:
```
- foo
+ `a + b`
```
renders as
```
- foo
- a - &shy;<!-- .element: class="fragment" -->b
```

Example 3:
```
- foo
+ c = a + b
```
renders as
```
- foo
- c="true" =="true" a - b
```

**Expected behavior**
Fragmented list entries should always render identically to the corresponding non-fragmented list entry.

I believe that the problem is (or is related to) the [list fragment replacement code](https://github.com/MSzturc/obsidian-advanced-slides/blob/990ade6d1cdc9b9261a51d13ebb726c7b9c19df3/src/processors/fragmentProcessor.ts#L64) erroneously considering all `"+ "` sub-strings in a line, when in fact it should only consider those at the start of the line or preceeded only by whitespace, ie. those matching a regex of `"^\s*+"`.  (h/t @rueckstiess for finding the problematic code)

**Comment by MSzturc** [comment]
will be fixed with upcoming version
