### ISSUE TITLE
Code block padding bug using css/vs2015.css

### ISSUE THREAD

**Issue by 0atman** [MSzturc/obsidian-advanced-slides#189]
@MSzturc First off: thank you so much for this plugin, I'm literally launching [my youtube career](https://www.youtube.com/watch?v=Q3AhzHq8ogs&list=PLZaoyhMXgBzoM9bfb5pyUOT3zjnaDdSEP&index=1) using it (and you better believe I'm supporting you!)

**Describe the bug**
Something has slightly broken `vs2015.css` code blocks since the 20th of Oct  (Certainly it was broken by 10 Nov, I produced two videos on these dates, so can concretely say that the problem started in this period)

There is now extra padding at the bottom of code blocks:

**Samples to Reproduce**
Make a code block in Advanced Slides, using the `css/vs2015.css` theme, and note the new bonus asymmetrical padding at the bottom of the block.

![Screenshot_20221223_164433](https://user-images.githubusercontent.com/114097/209371720-440fe91c-3e0a-4e98-a6ef-b125fb85764a.png)

**Expected behavior**
This did not happen on or before the 20th of October, where it looked like this:

![Screenshot_20221223_164522](https://user-images.githubusercontent.com/114097/209371729-34c9430e-b8cf-427b-a6a9-a8dce4a68a4f.png)

I can't quite dig up where this has come from, the `highlight.js` file has not changed in 2022, so I suspect it's something local to Advanced Slides? The other themes don't have this problem, though they also don't have nice padding around them.

My workaround is to change the padding value from `css/vs2015.css` from 1em to 0.5 em, which doesn't fix the asymmetry, but makes it less obnoxious:

```css
pre code.hljs {
  display:block;
  overflow-x:auto;
  padding:0.5em;
}
```

Thank you again!

**Comment by 0atman** [comment]
I've fixed it by adding this to my frontmatter:

```css
.reveal .hljs {
  min-height: 50%;
}
```

Which overrides the 100% set in reveal.css

**Comment by MSzturc** [comment]
Ahhh wow nice find. To get more control i've wrapped every slide into a 100% x 100% grid with height of 100%.. i've added your fix into the reveal.css. Highlight.js should work as before with next version
