### ISSUE TITLE
Feature Request: Embed notes as Bullet points

### ISSUE THREAD

**Issue by MSzturc** [MSzturc/obsidian-advanced-slides#19]
> I know that obsidian is able to do it but they embed the note as iframe and i render it as part of the slide

In fact, this is why I wanted to have this feature in this slides plugin. Sometimes, I may embed notes under/as list items in ordinary Obsidian notes, just to show the hierarchical structure of the note content. Therefore, it would be great if this plugin can also support this feature, then I do not need to change the way of linking/embedding notes when creating slides. Or I can easily convert existing notes as slides. This is mainly for having a consistent workflow. :-)

Also, supporting embedding notes, whether as/under list items or not, in a way similar to iframe would be very helpful when the embedded notes have relatively long content. For instance, one may want to embed a note whose main content is multiple lines of code snippet.

- In such a case, this code snippet is mainly for the purpose of demonstration. Therefore, it would be great if there can be some kind of box/iframe (I forgot the term for that 😅) of a size that depends on the size of the slide.
- For the remaining content of the note, one can use some kind of slide bar to scroll up and down.
- Another benefit of embedding notes like this is to avoid not being able to show the complete content of the note when the content is relatively long.

Of course, there can be a separate option for choosing whether to render the embedded notes as part of the slides or in a way similar to iframe. Such an option can be configured in the front matter for all slides, or it can be configured on a per slide basis.

_Originally posted by @wenlzhang in https://github.com/MSzturc/obsidian-advanced-slides/issues/8#issuecomment-998092108_

**Comment by MSzturc** [comment]
I understand. I'll see if something (in reveal.js) is possible.

My vision for Advanced Slides was to use the standard that Reveal.js set and to transform the obsidian notes into them.If we can manage to display the representation as you imagine it in reveal.js, then I can write a transformer for it.What I don't want, however, is to add functionality to reveal.js or to develop a derivative of it, as I simply don't have the time for this.

**Comment by wenlzhang** [comment]
> What I don't want, however, is to add functionality to reveal.js or to develop a derivative of it, as I simply don't have the time for this.

I totally understand this.

Not sure if it helps, the Jupyter extension RISE also uses reveal.js for creating slides, and it has a similar feature:
https://rise.readthedocs.io/en/stable/customize.html#enable-a-right-scroll-bar

**Comment by MSzturc** [comment]
moved to Roadmap
