### ISSUE TITLE
Vertical sub-slides only go one level deep

### ISSUE THREAD

**Issue by RobertTalbert** [MSzturc/obsidian-advanced-slides#191]
According to the documentation using the `--` separator within a slide is supposed to create a "vertical" sub-slide. For me, this is working on the first sub-slide in a vertical sequence. But using the same notation to create additional sub-slides in that sequence just puts a literal `--` on the second slide along with the text. Here's a screenshot: 

<img width="1163" alt="Screen Shot 2023-01-15 at 13 48 04 PM" src="https://user-images.githubusercontent.com/3129186/212560892-1ceef707-5669-4552-a0d7-062a9bc30eb5.png">

Obsidian version 1.1.12 insider build (although it was doing this on the official earlier releases too)
Advanced slides v. 1.19.0

**Comment by MSzturc** [comment]
Im not able to reproduce this one. 

Try if this snippet works:

```
Slide 1

---

Slide 2

--

Slide 3

--

Slide 4
```

**Comment by RobertTalbert** [comment]
It appears to work now with the latest plugin update.
