### ISSUE TITLE
"open in browser" Conflict with Open With Link Plugin

### ISSUE THREAD

**Issue by ksdavidc** [MSzturc/obsidian-advanced-slides#192]
**Describe the bug**
the "open in browser" button appears to have a conflict with  the Open Link With (OLW) plugin

log attached:
[obsidian.md-1674090867298.log](https://github.com/MamoruDS/obsidian-open-link-with/files/10452507/obsidian.md-1674090867298.log)

The issue could be with OLW and I have referenced them [here](https://github.com/MamoruDS/obsidian-open-link-with/issues/20#issue-1548372765).

**Samples to Reproduce**
Create a vault with just these plugins.
The link works with OLW off, and fails when OLW on.

**Expected behavior**
that the link would open in browser even with OLW on.

**Comment by MSzturc** [comment]
Did should be fixed by updating OLW plugin to 0.1.10
