### ISSUE TITLE
Sharing slides via URL

### ISSUE THREAD

**Issue by nicfab** [MSzturc/obsidian-advanced-slides#195]
Is there a way to share the slides?
I aim to allow the recipient only to see the slides without any intervention.
Indeed, I see that it’s possible to see the slides via the browser but only locally.
Can we share the slides by simply sending a link?

**Comment by MSzturc** [comment]
No that's not possible since we don't have an infrastructure that's hosts slides. You have two options:
- Export slides as html or pdf and send the exported files through mail.
- Make a public vault that you host on github as git pages and access the slides through git pages

**Comment by nicfab** [comment]
> No that's not possible since we don't have an infrastructure that's hosts slides. You have two options:
> 
> * Export slides as html or pdf and send the exported files through mail.
> * Make a public vault that you host on github as git pages and access the slides through git pages

Thank you.
