### ISSUE TITLE
Plugin Missing from Community Plugin Search

### ISSUE THREAD

**Issue by jeetsukumaran** [MSzturc/obsidian-advanced-slides#196]
**Describe the bug**

Searching for "advanced" or "slides" from inside Obsidian does not bring up this plugin.

**Samples to Reproduce**

In Obsidian, go to settings, community plugins, browse. Try to find the "Advanced Plugin".

**Expected behavior**

This plugin is found.

**Comment by fredtempez** [comment]
Confirmed
