### ISSUE TITLE
The syntax for embedding a page slide in version 1.19 is not working.

### ISSUE THREAD

**Issue by yangruijingdepengyou** [MSzturc/obsidian-advanced-slides#197]
```slide
{
      slide: [[slidesname]],
      page: 1
}
```
![image](https://user-images.githubusercontent.com/86993516/218380620-d142c40d-ef76-4dfe-a3bb-fa6b2cf435c6.png)

**Comment by MSzturc** [comment]
will be fixed in 1.20

**Comment by KoichaDev** [comment]
> will be fixed in 1.20

Still not working on version 1.20
