### ISSUE TITLE
Advanced Slides not available in the store

### ISSUE THREAD

**Issue by Srylax** [MSzturc/obsidian-advanced-slides#199]
**Describe the bug**
Advanced Slides is not available in the obsidian Plugin Store. Both Web Store and Obsidian Store are affected. 

**Samples to Reproduce**
Open [https://obsidian.md/plugins](https://obsidian.md/plugins) and search for "Advanced Slides"

**Expected behavior**
Advanced Tables to show up.

**Comment by MSzturc** [comment]
duplicate to #183
