### ISSUE TITLE
Pictures not exported in html export

### ISSUE THREAD

**Issue by fredtempez** [MSzturc/obsidian-advanced-slides#201]
The images are not exported, it is necessary to copy them to the export folder. See attached slideshow.
Files and links is set up like this : 
relative path to file.
No wikilinks.
OS is Win 11 or Win 10, same issue.
Thanks !

[Export picture issue.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/10817384/Export.picture.issue.zip)

**Comment by MSzturc** [comment]
You're right, there was a bug in the image processor, will be fixed in next release!

**Comment by ybabel** [comment]
Hi, I have the same bug, and there has not been any release since 1yr. Is the next release scheduled soon ?
Can you tell where is the bug so that I can correct it manually in the meantime ?
