### ISSUE TITLE
Print (save to pdf) is broken in Firefox

### ISSUE THREAD

**Issue by mimavox** [MSzturc/obsidian-advanced-slides#208]
Cannot get the print (save to pdf) functionality to work in Firefox (110.0). Only the first sllide is included in the pdf, the rest are empty with background-color only. In Google Chrome, it works fine.

**Samples to Reproduce**
Open print link in Firefox.

**Expected behavior**
All pages should render correctly.

**Comment by MSzturc** [comment]
You should open a bug ticket at firefox repository. All Advanced Slides does is to create a html+css file that has to be rendered in firefox correctly ( since it works on safari & chrome based browsers without any issues)
