### ISSUE TITLE
Adding PDF pictures to slides

### ISSUE THREAD

**Issue by irzhegalova** [MSzturc/obsidian-advanced-slides#209]
Hey, great plugin! I have already created 3 presentations with it and I absolutely love it.
I am looking for a way to add PDF picture to my slides, as exporting to SVG leads to some parts of pic shifted, png with high DPI is heavy enough, and anyway my original pics are PDFs. 

Best solution would be to allow using PDF one-page pics as regular pics.

But as an alternative it could be just using [reveal.js plugin](https://www.npmjs.com/package/reveal-pdf?activeTab=readme) as was suggested by [#186](https://github.com/MSzturc/obsidian-advanced-slides/issues/186#issue-1496853826)

Thank you in advance :)

**Comment by MSzturc** [comment]
The problem here is that the underlaying tech doesn't support pdfs as image source there i wont be able to implement an adapter to integrate them into advanced slides.
