### ISSUE TITLE
more menu (3 dots) does not appear in Slide Preview

### ISSUE THREAD

**Issue by scbarton** [MSzturc/obsidian-advanced-slides#248]
**Describe the bug**
The more menu (3 dots) does not appear in Slide Preview

I'm using Advanced Slides 1.20.0 and Obsidian 1.4.2 on a MacBook Pro running macOS 13.5. 
**Samples to Reproduce**
with a presentation open, click on the Show Slide Preview Button

**Expected behavior**
I expected to see the three dot menu in the top right of the Slide Preview Pane
![Screenshot 2023-08-10 at 6 41 49 PM](https://github.com/MSzturc/obsidian-advanced-slides/assets/1451344/577dc733-bd3a-4405-8c93-b58a01ebb80f)

**Comment by EvanEdwards** [comment]
This makes it impossible to export to HTML, as far as I can tell.

**Comment by DHSYan** [comment]
Hi @scbarton, I have encountered the same issue,

Here's what I did to fix it, 

I (re)enabled "Show table title bar" under "Advanced" in "Appearance" in settings.

Hope this helps!

**Comment by scbarton** [comment]
Yep, that did it, thank you!  I guess we need to have the title bar enabled to see the more menu and other controls.
