### ISSUE TITLE
Control OBS with Obsidian Advanced Slides, help creating plug-in

### ISSUE THREAD

**Issue by UUoocl** [MSzturc/obsidian-advanced-slides#255]
OBS is a tool for live streaming or recording video. This feature request is to send commands to OBS as the OAS slides transition between slides. 

I started to create an Obsidian Advanced Slides (OAS) plug-in that connects OAS to [OBS](https://obsproject.com/) via webSockets.

The plug-in is described in this [YouTube video](https://www.youtube.com/watch?v=P3NDWLdrQF0) and this
[Github repo has an Obsidian vault with the code](https://github.com/UUoocl/Obsidian_AdvancedSlides_Demo_Vault/tree/main)

I don't know how to code the plug-in into the OAS officially.  

I would like to see this idea in OAS, but I'd need help to integrate it into OAS

A standalone version of this idea can be found in this github repo [Reveal-Electron-Player](https://github.com/UUoocl/Reveal-Electron-Player).

**Comment by Origena** [comment]
Your great vault no longer work with version 1.20.00 transition between scene do nor work .

**Comment by UUoocl** [comment]
I revisited my project to control OBS from Advanced Slides. Now I understand how it fits in to Obsidian Advanced Slides.  
Obsidian Advanced Slides is a  brilliant plug-in.  Thanks for creating it and keeping the repo available.
