### ISSUE TITLE
No slides showing

### ISSUE THREAD

**Issue by lucasrodwell** [MSzturc/obsidian-advanced-slides#270]
**Describe the bug**
Nothing showing in slides pane.

**Samples to Reproduce**
"Show slide view" on any slide, get following error in console:
`plugin:obsidian-advanced-slides:226 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3000') does not match the recipient window's origin ('app://obsidian.md').`
Get the same error on refresh and show grid.
Obsidian in installed from obsidian_1.4.16_amd64.deb

**Note**
A similar bug has happened to me before, and previously managed to solved it by extracting https://github.com/hakimel/reveal.js/archive/master.zip into the obsidian plugins folder (presumably it was blocked from being downloaded). However, this no longer works.

**Comment by lucasrodwell** [comment]
I think I may have had two vaults open, both using advanced slides on the same default port 3000. Just needed to change the port number... Solved, changing the port number fixed it.

**Comment by CEbbinghaus** [comment]
> I think I may have had two vaults open, both using advanced slides on the same default port 3000. Just needed to change the port number... Solved, changing the port number fixed it.

Thank you so much. That is exactly the problem I had. Surely there is a way to either programmatically choose a different port per Obsidian instance or at least warn the user as to why the show slide doesn't work
