### ISSUE TITLE
Lines in code blocks are aligned to the center

### ISSUE THREAD

**Issue by attila-fazekas** [MSzturc/obsidian-advanced-slides#273]
**Describe the bug**
Lines in code blocks are aligned to the center:
![Screen Shot 2023-11-12 at 15 35 02](https://github.com/MSzturc/obsidian-advanced-slides/assets/24605630/90680aa6-d92e-484d-af59-de93d661343d)

**Samples to Reproduce**
Just copy-paste the example code block from [here](https://mszturc.github.io/obsidian-advanced-slides/basic-syntax/codeblocks/) and remove the indentation on the last line (before the ```) as described [here](https://github.com/MSzturc/obsidian-advanced-slides/issues/165#issuecomment-1467471331)

**Expected behavior**
I would expect the code in code blocks to always be aligned to the left:
![image](https://github.com/MSzturc/obsidian-advanced-slides/assets/24605630/f180ecf5-6dc9-40d2-9106-f908ef907fd8)

I have tried many examples, but none of them worked. I am sort of new to Obsidian and might be overlooking something.

**Comment by agentlibre** [comment]
You can specifiy the command you want to apply for the block if you write the command next to it.

Example (changing font-size + text-align):

```
::: block <!-- element style="font-size:37px; text-align:left;"-->

My math formulas

:::

```

You're welcome

**Comment by attila-fazekas** [comment]
Thanks!
It's funny – I just launched Obsidian to try out your example, and all my code samples worked without touching anything. Closing this issue.
