### ISSUE TITLE
Request - possible to include print to pdf functionality?

### ISSUE THREAD

**Issue by abhuva** [MSzturc/obsidian-advanced-slides#31]
In Reveal.js its possible to extend the webbrowser presentation like so: http://localhost:8000/?print-pdf and save it as a pdf.
This seems to not correctly work with the presentations i get within obsidian:
I show them in webbrowser, extend the url, save it - but its giving a wrong output.
Mostly its duplicating the same slide over and over, sometimes rendering them in a wrong way.

Using Chrome, and the demo from Reveal.js works fine.
Not entirely sure whats causing it.

If possible it would be fantastic to get it working.

EDIT: seems i was wrong, when i right-click and choose PRINT then its not working, but i use ctrl-p to open the print-dialog, i get the correct settings and it works... kind of strange but i guess i can live with it.

**Comment by MSzturc** [comment]
With 1.2.0 it's possible to print the presentation properly (in the Preview Window->more Options->Print Presentation)

**Comment by KFrancoD** [comment]
> With 1.2.0 it's possible to print the presentation properly (in the Preview Window->more Options->Print Presentation)

Hi, while I was trying to print presentation, the default orientation is portrait and only half A4 paper is filled. When I changed it to landscape, the presentation slides will be oversized. Any adjustment i should make so that I can fit a slide to a A4 paper?
