### ISSUE TITLE
Background Images are difficult to work with

### ISSUE THREAD

**Issue by abhuva** [MSzturc/obsidian-advanced-slides#32]
I just stumbled upon the following issue:
I upload my slides to github pages, the workflow is pretty straightforward: 
- showing in browser
- saving it from browser
- upload the files (html + directory) to my repository

This works great and the internal linking of pictures are not broken.
With background pictures this doesnt work.
I am using the following command:

!-- .slide: data-background-image="/pathtofile/file.jpg" -->

this works in obsidian and locally. But when i save the site to upload it, the "file.jpg" doesnt appear in the attachments folder and of course the linking doesnt work also.
I guess that those kind of links doesnt get handled well.

I am not sure if it is possible to fix it, i can manually update the links and stuff in the resulting files, but i was hoping to use more background-pictures and it gets tedious to manually update them.

Maybe i also miss an easy workaround here.

**Comment by MSzturc** [comment]
Yeah that doesn't work (currently). I plan to add an export functionality in the next versions, so stay tuned ;-)

**Comment by MSzturc** [comment]
I've implemented an export to html feature with 1.3.0, have fun testing.
