### ISSUE TITLE
When open presentation, some bugs come.

### ISSUE THREAD

**Issue by Quorafind** [MSzturc/obsidian-advanced-slides#33]
![image](https://user-images.githubusercontent.com/13215013/147865437-3e773cf6-4216-4c07-b871-7b3aa48955e3.png)

**Comment by MSzturc** [comment]
Ohhh nice find, seams like rendering of slides in subfolders had a bug, will be fixed with 1.3.1

**Comment by MSzturc** [comment]
This issue should be fixed with 1.4.0, please retest
