### ISSUE TITLE
Support For Mobile 

### ISSUE THREAD

**Issue by 42sol-eu** [MSzturc/obsidian-advanced-slides#34]
Would it be hard to do a support for mobile devices for this plugin?

**Comment by MSzturc** [comment]
That’s going to be difficult. Large parts of the core would have to be rebuilt for this, as they are based on nodejs libraries, which are not available on mobile. This will be an issue, if at all, for version 2

**Comment by KFrancoD** [comment]
Thanks for considering this!

**Comment by KFrancoD** [comment]
> That’s going to be difficult. Large parts of the core would have to be rebuilt for this, as they are based on nodejs libraries, which are not available on mobile. This will be an issue, if at all, for version 2

thank you for considering this!

**Comment by MSzturc** [comment]
moved to Roadmap

**Comment by noseshimself** [comment]
> That’s going to be difficult. Large parts of the core would have to be rebuilt for this, as they are based on nodejs libraries, which are not available on mobile. This will be an issue, if at all, for version 2

If you turn it into a PWA you could include the entire node.js and it would be acceptable as Android application (or as a - self-hosted or not - web-based service ChromeOS would turn it into an application). That should be a lot less work. Even a web-assembly might make sense.

**Comment by globalhuman** [comment]
Hi, I am confused about the status of this feature request.

Is it "completed" as it appears to be indicated on the roadmap or does it require further work?

I would love to be able to use mobile devices(android, iOS) as well to utilise this plugin
