### ISSUE TITLE
Broken links for frontmatter additional css scripts

### ISSUE THREAD

**Issue by rxian** [MSzturc/obsidian-advanced-slides#38]
In my frontmatter, I have

```
css: 
- css/some-custom.css
```

and in previous versions of obsidian-advanced-slides, it loads the script in plugin's css folder just fine. But a recent update seems to have broke it:

![](https://i.imgur.com/BE3hEmS.png)

Finally, thank you for contributing this plugin to Obsidian! It has allowed me to customize reveal.js much more straightforwardly.

**Comment by MSzturc** [comment]
Nice find, will be fixed with next version
