### ISSUE TITLE
Feature Request: Display PDF Dokuments in Advanced Slides

### ISSUE THREAD

**Issue by Hunanbean** [MSzturc/obsidian-advanced-slides#41]
I am not sure if this is an actual issue, or intentional.
Either using the Obsidian built in method, or using Better PDF plugin, PDFs do not display when viewing Advances Slides.

Thank you

**Comment by MSzturc** [comment]
Yeah thats right, PDF's are currently not supported in Advanced Slides and for the near future they wont because of the workflow how i handle pdf's currently, but i will have a look at it for the next major release of advanced slides

**Comment by MSzturc** [comment]
Moved to Roadmap (https://github.com/MSzturc/obsidian-advanced-slides/projects/1#card-81813331)
