### ISSUE TITLE
Plugin ignores markdown image resize when using markdown style links

### ISSUE THREAD

**Issue by samaursa** [MSzturc/obsidian-advanced-slides#42]
Obsidian's regular presentation mode recognises image resize in markdown i.e. `![text|100](image.png)` or `![text|100x100](image.png)`

However, the plugin ignores these resize commands. Is it possible to resize images similar to how the plugin allows `![[image.png|100x100]]`?

**Comment by MSzturc** [comment]
will be fixed in upcoming version
