### ISSUE TITLE
Feature Request: Header/Footer

### ISSUE THREAD

**Issue by geblanco** [MSzturc/obsidian-advanced-slides#44]
Hi!

First of all, thank you for this great plugin!! It really does the job :)

It could be great to have the ability to inject a header/footer to every slide, just like in any other slideshow platform.
As a first approach, it might be done by creating custom css header and footer classes with a floating, position-fixed div.
Then maybe, some metadata variables in the document could customize the icon (just like the theme variable), though I don't quite see how to insert a title for each slide.

What do you think?
Best,

**Comment by stefanopagliari** [comment]
I would be interested in this feature as well

**Comment by MSzturc** [comment]
me2😄

This one has a high priority for me but currently im on the edge to start a new project so i have no spare time to spent for plugin development

**Comment by geblanco** [comment]
Hi @MSzturc,

I understand, open source has this caveats...
Maybe you can compile a non-exhaustive list of ToDo and let us help on what we can?
I'm not proficient in css, but can help on the TS/JS bits.

Best,

**Comment by MSzturc** [comment]
Feel free to pick an item from the product roadmap.

https://github.com/MSzturc/obsidian-advanced-slides/projects/1

**Comment by MSzturc** [comment]
I would suggest to start with this one:

https://github.com/MSzturc/obsidian-advanced-slides/issues/42

It's a small extension of the image preprocessor. A good start to Into the Code base.

If you have questions, text me in obsidian discord.

**Comment by MSzturc** [comment]
will be implemented with 1.9
