### ISSUE TITLE
Integration with Admonitions plugin?

### ISSUE THREAD

**Issue by jcmoral90** [MSzturc/obsidian-advanced-slides#48]
Could be considered a future collaboration with the admonition plugin into Advanced Slides?

Greetings,

**Comment by WilliamCappelletti** [comment]
+1

**Comment by Liong1976** [comment]
+ 1

**Comment by MSzturc** [comment]
Ohh dear... this is a tough one, reveal doesn't support by itself, so i would have to implement most of the business logic in the advanced slides transformation layer

**Comment by MSzturc** [comment]
https://github.com/szacchino/admonition-revealjs

**Comment by MSzturc** [comment]
I've decided to only support Callouts at the moment, since the synthax parsing based on the feature set of admonition plugin is too complex and would take too much time for the benefit it would get the average user over callouts.

Please have a look at #64

**Comment by ksdavidc** [comment]
Ah, too bad. Understandable, but alas for my ends I need admonitions...maybe someday...I really like your plugin though...

**Comment by Yiming-M** [comment]
One possible solution is to enable "Use CSS Snippet for Custom Callouts" in Admonition. This is a workable solution, except that the selected colors and icons won't be displayed. See https://github.com/MSzturc/obsidian-advanced-slides/issues/326.
