### ISSUE TITLE
Internal Links to Images Incorrect

### ISSUE THREAD

**Issue by Servinjesus1** [MSzturc/obsidian-advanced-slides#49]
The plugin fails to find the correct image when using internal links to images within a different folder than the presentation. If the image name is unique across the Vault and the image is not in the same folder as the presentation Note, the plugin will fail to find the image. If the name is not unique, or partially matches other image names even, it finds a random image of the set it matches to. In my experience it found an image called `Wedge Image.jpg` buried deeply in my Vault when looking for `Image.jpg`

Obsidian finds the right image still, leading to cases where Preview Mode will show one thing, and the slides another.

**Comment by MSzturc** [comment]
will be fixed with 1.7.2
