### ISSUE TITLE
Hightlights in code blocks

### ISSUE THREAD

**Issue by neugartf** [MSzturc/obsidian-advanced-slides#50]
Hey!

Thanks for this plugin. This is not really an issue, but rather a question. I didn't find this in the docs:

How can you use the `data` elements like shown here? https://revealjs.com/code/#line-numbers-%26-highlights

This kind of works
```
#### Hello from Cover Page
---
<!-- element style="line-height: 3rem;"-->
- test dfkldsfjklsd
- sdfjlsdfkljlk 

<pre>
<code data-line-numbers="3-5|8-10|13-15">
<table>  
	<tr>    
		<td>Apples</td>    
		<td>$1</td>    
		<td>7</td> 
	</tr>  
	<tr>    
		<td>Oranges</td>   
		<td>$2</td>  
		<td>18</td> 
		</tr>
</table>
</code></pre>
```

but introduced additional tags like `tbody`.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/6741676/153932317-198aa0bb-0627-4ca5-84c1-dd098995a42e.png">

**Comment by MSzturc** [comment]
I missed this feature in the last few weeks, too

Im no really sure what a good markdown syntax will be for highlighting line in code.

I'll do some research to see if there are already solutions in other markdown-based tools that I implement for advanced slides as well
