### ISSUE TITLE
New setting request: ability to insert a preamble to every slide for CSS/JS

### ISSUE THREAD

**Issue by trenta3** [MSzturc/obsidian-advanced-slides#51]
Hi! Thank you for this very useful project.
I'm lately finding myself copying a bit of custom css styles in every deck of slides I make. It would be nice if it could be pasted directly into the options of the plugin and then automatically included.

Also I was thinking of asking to include a MathJax preamble loaded from a file like the "Extended MathJax" plugin does inside of obsidian, but I think that just the ability to include custom code in every slide deck should provide the ability to do it autonomously and without too much effort.

**Comment by MSzturc** [comment]
with 1.9 there will be a templating feature that could be used for for preamble code. stay tuned ;-)
