### ISSUE TITLE
Digit followed by closing parenthesis ')' followed by space and text won't render

### ISSUE THREAD

**Issue by rxian** [MSzturc/obsidian-advanced-slides#53]
The markdown parser used by this plug-in won't render the following strings:

- `(1) text`
- `1) abc`

**Comment by rxian** [comment]
Seems that this issue is caused by regex in [fragment processor](https://github.com/MSzturc/obsidian-advanced-slides/blob/19daa5b20a42fafebbbd31bf720289f5c0ccacd7/src/processors/fragmentProcessor.ts#L8)

Instead of 

```javascript
orderedListRegex = /\d\) /g;
```

maybe it should've been

```javascript
orderedListRegex = /^\d\) /g;
```

**Comment by MSzturc** [comment]
will be fixed with 1.7.0
