### ISSUE TITLE
Multiple footnotes on same slide out-of-order

### ISSUE THREAD

**Issue by rxian** [MSzturc/obsidian-advanced-slides#54]
When there are multiple footnotes on the same slide, the footnote will not be rendered in the order of when first appeared.

```markdown
[^1] [^2] [^3]

[^1]: fn1
[^2]: fn2
[^3]: fn3
```

gets

<img width="213" alt="Screen Shot 2022-02-21 at 12 45 26 PM" src="https://user-images.githubusercontent.com/8406802/155011596-3a2e10f0-681d-45b4-9331-3ea78c7e5485.png">

**Comment by rxian** [comment]
I was able to get rid of this issue by removing the `g` flag in regex in [footnote processor](https://github.com/MSzturc/obsidian-advanced-slides/blob/19daa5b20a42fafebbbd31bf720289f5c0ccacd7/src/processors/footNoteProcessor.ts#L5), although I am not sure why this flag is needed... 😶‍🌫️

**Comment by MSzturc** [comment]
will be fixed with 1.7.0
