### ISSUE TITLE
Compatibility with Highlightr-Plugin

### ISSUE THREAD

**Issue by ivanddm** [MSzturc/obsidian-advanced-slides#56]
Thanks for a really nice plugin for presentations. Haven't found one as good and simple to use as this one in other applications (e.g., logseq, vs-code, etc.)

I know that your plugin supports the default obsidian highlights with `==...==`. I would like to suggest also adding compatibility with the [Highlightr-Plugin](https://github.com/chetachiezikeuzor/Highlightr-Plugin) to allow for different highlighting colors and styles. The default presentation mode is compatible with that plugin, so would love to have that as well in your advanced slides plugin.

Thanks in advance!

**Comment by MSzturc** [comment]
I've done a few tests with the plugin and it worked out of the box.

![image](https://user-images.githubusercontent.com/4275753/164199074-0ea85c3e-3cdf-4f42-aa0d-80b3d6273bda.png)

**Comment by MSzturc** [comment]
works with 1.8.1
