### ISSUE TITLE
Fragments not displayed correctly when list item has bolded text or math

### ISSUE THREAD

**Issue by jdluque** [MSzturc/obsidian-advanced-slides#57]
If my list item has bolded (using both `__text__` and `**text**`) text or math (`$y=mx+b$`), then the fragmented list shows everything but the bolded text/math. Proceeding to the next slide will incrementally show the missing bolded text or math.

**Comment by MSzturc** [comment]
Can you provide me a sample, im not able to reproduced this problem
![Bildschirmfoto 2022-03-25 um 10 42 07](https://user-images.githubusercontent.com/4275753/160096075-31efdcf4-e199-4f0f-8096-18aa6170c68f.png)

**Comment by MSzturc** [comment]
should be fixed with 1.7.1 please retest

**Comment by jdluque** [comment]
It's working now. Thanks!
