### ISSUE TITLE
Images inside sub-folder were not displayed

### ISSUE THREAD

**Issue by sheldonxxd** [MSzturc/obsidian-advanced-slides#58]
I found a bug of image path parsing. I had specified the sub-foler `08-Assets` to store any attachments including images. When I insert the image into the page either in wiki (`![[img.png]]`) or markdown style (`![](img.png)`), nothing is rendered in the slide preview. Finally, I solved this problem in a dirty way. I modified the `main.js` file as below:

![image](https://user-images.githubusercontent.com/42539486/158717852-aaf63d11-d456-4c4a-8deb-b67e2b3f8f6b.png)

obsidian-advanced-slides is an useful plugin, I hope the author can solve this small bug.

**Comment by MSzturc** [comment]
Hmm... im not able to reproduce this behavior..

![Bildschirmfoto 2022-03-25 um 10 37 30](https://user-images.githubusercontent.com/4275753/160095332-342b9df6-b1d4-43b9-b96e-432942a8bfe0.png)

May i ask you to upload an screenshot of your obsidian->settings->files & links

**Comment by sheldonxxd** [comment]
> Hmm... im not able to reproduce this behavior..
> 
> ![Bildschirmfoto 2022-03-25 um 10 37 30](https://user-images.githubusercontent.com/4275753/160095332-342b9df6-b1d4-43b9-b96e-432942a8bfe0.png)
> 
> May i ask you to upload an screenshot of your obsidian->settings->files & links

![image](https://user-images.githubusercontent.com/42539486/160101252-2c4223ad-d6dc-421b-962d-13936ff72286.png)

**Comment by MSzturc** [comment]
It might be related to the same issue that is documented in (https://github.com/MSzturc/obsidian-advanced-slides/issues/52). Does the fix alex described there also fixes your issue?

**Comment by sheldonxxd** [comment]
No, but this issue is gone when I use another new vault (as you did). I guess it might be caused by some incompatible setting from obsidian theme. Anyway, thank you a lot.
