### ISSUE TITLE
How to apply effects on fragments?

### ISSUE THREAD

**Issue by wenlzhang** [MSzturc/obsidian-advanced-slides#6]
Is it possible to apply effects on fragments like below?
https://revealjs.com/fragments/

**Comment by MSzturc** [comment]
Fade in 
    
    Fade out 
    
    Highlight red 
    
    Fade in, then out 
    
    Slide up while fading in 

I will add Section into the documentation in the future

**Comment by wenlzhang** [comment]
Thank you for the help!

**Comment by wenlzhang** [comment]
I also tried to test fragment orders, but it did not work for me with the following examples. Am I not doing it correctly?

```
- Appears last <!-- .element: class="fragment" data-fragment-index="3" -->
- Appears first <!-- .element: class="fragment data-fragment-index='1'" -->
- Appears second <!-- .element: class="fragment data-fragment-index='2'" -->
```
