### ISSUE TITLE
Feature Request: Oveflow: scroll

### ISSUE THREAD

**Issue by PeterEhses** [MSzturc/obsidian-advanced-slides#66]
Thanks for making obsidian useful for Presentations!
The one thing I'm missing from this plugin is the option to make a given section, or at least the entire slide, scrollable. 
I often have long lists / tables that aren't easy to split, so having a scroll flag / container to apply to these would be great. 
Alternatively, the entire slide could scroll if overflow is present (i.e. overflow-y: auto).

**Comment by MSzturc** [comment]
Hmm... thats tricky, for most of my workflows my customer needs a pdf Version of my presentation as handout therefore ive tried to make the themes  static for most of the Layouts. You could create an own theme that overflows.

**Comment by rxian** [comment]
I achieve this with a [`scrollable.css`](https://gist.github.com/rxian/0b48877580b49b3588c78b90a6515a98), which I enable by including it in the preamble:

```
---
css: 
- css/scrollable.css
---
```
