### ISSUE TITLE
[Bug report] <p> around image "absorbs" any further content

### ISSUE THREAD

**Issue by annargrs** [MSzturc/obsidian-advanced-slides#67]
Plugin version 1.72 in Obsidian 0.14.6

Expected behavior: a separate `<p>` element with class "footer" after the image element

Markdown source:

```
# Title

![[myimage.jpg]]

Image credit: J. Smith <!-- element class="footer" --> 

```

Current behavior: the footnote text and its class gets "absorbed" into the `<p>` element containing the image itself, and so styling it separately is impossible.

```
<h2 id="title">Title</h2>
<p style="line-height: 0" class="footer"><img src="/presentations/img/myimage.jpg" alt=""></p>
Image credit: J. Smith
<!-- -->
```

Update: this also happens with `<ul>`. Any paragraph following a list gets "absorbed" into it.

**Comment by MSzturc** [comment]
fixed since 1.17 please retest
