### ISSUE TITLE
[Bug report] Fragments apply to sub-paragraph units

### ISSUE THREAD

**Issue by annargrs** [MSzturc/obsidian-advanced-slides#68]
Plugin version 1.72 in Obsidian 0.14.6

Expected behavior:  makes the whole line/paragraph it applies to appear

Current behavior: if that line/paragraph has inner markup, the animation will apply only to the marked-up element. If any math expressions are present, one of them will be animated instead of the line/paragraph.

Markdown source:

```
# Title

* **bullet 1:** some text   <!-- element class="fragment" -->
* *bullet 2: some more text   <!-- element class="fragment" -->

```

Bullet 2 will be fully animated, while for the first one only the "bullet 1" text will be animated.

**Comment by MSzturc** [comment]
Okay, i've played a bit with your example and noticed that's not as easy to fix as expected. The element annotation does not know which node is its parent.

An good workaround would be using [Fragmented Lists](https://mszturc.github.io/obsidian-advanced-slides/extend-syntax/fragmentedlists/)

```
# Title

+ **bullet 1:** some text
+ bullet 2: some more text
```
