### ISSUE TITLE
[Feature Request] Collaborating with Hover Editor: show slide preview pane directly in a popover

### ISSUE THREAD

**Issue by XMB-7** [MSzturc/obsidian-advanced-slides#69]
Thanks for your time and effort on this awesome plugin. I use it heavily on embedding webs and videos into Obsidian. Sometimes I think it would be even more convenient if we were allowed to directly open the slide preview in a popover which can be supported by a third-party plugin named Hover Editor. Thanks for reading this.

![图片](https://user-images.githubusercontent.com/65625632/164258928-b757853b-99a2-4dfa-8f25-854e7ca4747f.png)

**Comment by MSzturc** [comment]
Nice idea, but im not sure if it's practical. Most of my slides that are a bit more complex take 2-2,5sec to render

**Comment by MSzturc** [comment]
Since 1.11.0 it's possible to embed slides into notes(https://mszturc.github.io/obsidian-advanced-slides/features/embedslide/). Can you try if it works with hover editor?

**Comment by XMB-7** [comment]
@MSzturc 
Thanks for this amazing feature, but not sure if I misunderstood how to use it...
![image](https://user-images.githubusercontent.com/65625632/168000319-9f3d3be5-925e-404d-be7d-3a79574abe9c.png)

---

I've also tried to remove the file suffix or embed a pdf, but both do not work.
I'll switch off other plugins to see if there is a conflict later.

**Comment by MSzturc** [comment]
Ahh you misunderstood that feature. It's not possible to embed ppt or pdf pages. The goal was, to integrate slides you designed with advanced slides to embed into Obsidian notes to reference them or maybe to make notes based on them.
