### ISSUE TITLE
Support embedding local media files outside an Obsidian vault

### ISSUE THREAD

**Issue by wenlzhang** [MSzturc/obsidian-advanced-slides#7]
It would be great if one can embed media files like audio and videos outside the Obsidian vault.

**Comment by MSzturc** [comment]
Since obsidian does not support this, I have not provided the option in advanced slides either. 

Had the same problem as you. I solved it by creating a symlink in my vault to the folder in which, for example, my pictures are.

**Comment by wenlzhang** [comment]
> I solved it by creating a symlink in my vault to the folder in which, for example, my pictures are.

Thanks for the solution.

Not sure if it helps, the Annotator plugins support local PDF files outside the vault:
https://github.com/elias-sundqvist/obsidian-annotator/issues/80

**Comment by MSzturc** [comment]
Thx for the input, i didn't know that Obsidian supports file protocol.

I will have a second look at it and try to integrate local media outside the vault by using file url format like:

`![Image](file:/Users/mszturc/Desktop/howToUse.png)`

**Comment by MSzturc** [comment]
Got it working, will be included in 0.15.0
