### ISSUE TITLE
Questions about login

### ISSUE THREAD

**Issue by zhl111** [MSzturc/obsidian-advanced-slides#70]
I've seen people use the slide plugin as a built-in browser. I tried to do the same, but had problems with to not being able to log in. I've consulted with some people and some don't have this problem. I would like to know how to solve this problem, thanks

![image](https://user-images.githubusercontent.com/29135984/164406714-61d7030b-ad96-4b3f-a37a-9dcbdca2c711.png)

**Comment by MSzturc** [comment]
It was never intended to be an built in browser and its not possible to browse more complex webpages since all pages are sandboxed and are not allowed to store cookies or websessions.

**Comment by zhl111** [comment]
I feel bad to hear you say that, it would be a great extension.
