### ISSUE TITLE
Missing frontmatter option for slideout menu?

### ISSUE THREAD

**Issue by simonmeggle** [MSzturc/obsidian-advanced-slides#71]
I am searching for a way to enable the **slideout menu** (https://mszturc.github.io/obsidian-advanced-slides/plugins/menu/).
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1897410/164913463-7177a1bf-69d3-452e-9fc8-052be6517e53.png">

Is it configured by the slide frontmatter? (I don't find any setting here...)
Thanks, 
Simon

**Comment by MSzturc** [comment]
By default most of the plugins are disabled. You can enable them in the Advanced Slides settings
