### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Sciemon** [MSzturc/obsidian-advanced-slides#72]
I tried to install this (likely very awesome) plugin by downloading the zip file and extracting it in the plugins folder as described. If I try to "enable" it in the obsidian plugins menu, I get the message "Failed to load plugin obsidian-advanced-slides". Looking at the developer console, it says that "Plugin failure: obsidian-advanced-slides Error: ENOENT: no such file or directory, open '...\.obsidian\plugins\obsidian-advanced-slides\main.js". This file is indeed missing.

**Comment by MSzturc** [comment]
the zip file doesn't contain advanced slides itself. It contains only the runtime to display slides created by advanced slides. The easierst way to use advanced slides is to install it through community plugins.

**Comment by Sciemon** [comment]
I got confused because the documentation says that it is not yet available as a community plugin.

**Comment by MSzturc** [comment]
Yeah i noticed that i've forgot to update this part of the documentation, will fix it in the upcoming version
