### ISSUE TITLE
Support for Obsidian Chat View

### ISSUE THREAD

**Issue by caasion** [MSzturc/obsidian-advanced-slides#73]
Currently, this plugin displays [chat view](https://github.com/adifyr/obsidian-chat-view) code blocks as normal code blocks. It would be great for this plugin to support [Obsidian Chat View](https://github.com/adifyr/obsidian-chat-view). This could be used to emulate a real chat dialogue and with many other uses.

**Comment by MSzturc** [comment]
Since reveal.js does not have a chat component, it would mean that I would have to redevelop large parts of the chat-view plugin. At the moment I don't see the effort for the benefit, so the topic is not a high priority for me

**Comment by MSzturc** [comment]
Added to Roadmap (https://github.com/MSzturc/obsidian-advanced-slides/projects/1#card-81812405)
