### ISSUE TITLE
</> Templates and vertical slides

### ISSUE THREAD

**Issue by delmenhorst** [MSzturc/obsidian-advanced-slides#74]
Hey,
i just discover that it isnt possible to use different templates on vertical slides.

**Comment by MSzturc** [comment]
Can you provide me an example?

**Comment by delmenhorst** [comment]
yes of course. :)
[Test.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/8644961/Test.zip)

**Comment by MSzturc** [comment]
Hmm.. can you describe your expectation a bit further? The Sample looks good in my Testvault. Maybe there is an interference with another plugin? Can you retry it in a fresh vault only with Advanced Slides installed?

<img width="424" alt="image" src="https://user-images.githubusercontent.com/4275753/167254488-05698fe1-eca5-48dd-8ac2-8f5754d29a87.png">

This is offtopic: but the links in the first slide work as well ;-)

**Comment by delmenhorst** [comment]
did it!  links a working now.

but still my result is this:
[localhost_3000__print-pdf.pdf](https://github.com/MSzturc/obsidian-advanced-slides/files/8645164/localhost_3000__print-pdf.pdf)

I am expectating your result... :)

**Comment by delmenhorst** [comment]
it seems the link issue, is a problem of the minimal theme i am using

**Comment by MSzturc** [comment]
mine exported without an issue... i have no clue whats diffrent.

[localhost_3000__print-pdf.pdf](https://github.com/MSzturc/obsidian-advanced-slides/files/8645835/localhost_3000__print-pdf.pdf)

if you export it to html, does the error still occur? If so please upload the zipped html presentation

**Comment by delmenhorst** [comment]
[Test.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/8645962/Test.zip)

**Comment by MSzturc** [comment]
Im not sure what causes your behavior but i enhanced the templating backend a bit, maybe it fixed your issue, please retry with 1.10.1

**Comment by MSzturc** [comment]
Closed since i wasnt able to reproduce issue. Please open a new issue when you have more details
