### ISSUE TITLE
Callout default background

### ISSUE THREAD

**Issue by jakeoung** [MSzturc/obsidian-advanced-slides#79]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/2376897/167756274-8b0cfa99-3c62-48c4-91eb-5ca4217e6f50.png">

Thanks for this wonderful plugin. I have an issue on the behaviour of callout. Without using `grid`, the background of callout is white, so that it looks not pretty on white background. (I use the `simple` theme.) I wonder if I miss something or it is expected.

**Comment by MSzturc** [comment]
Yeah i've noticed that too, will fix it in an upcoming version

**Comment by MSzturc** [comment]
will be fixed with the upcoming version
