### ISSUE TITLE
Error with internal note links

### ISSUE THREAD

**Issue by wenlzhang** [MSzturc/obsidian-advanced-slides#8]
I got error messages when using internal note links. It would be great if one can click the note link and go to the content on the note.

The slide:
```
---

## Note link

- [[Note link - 202112160000]]

```

The error:
```
Uncaught (in promise) RangeError: Invalid string length
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70146:62)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
    at InternalLinkProcessor.transformInternalLink (eval at <anonymous> (app.js:1), <anonymous>:70147:19)
```

**Comment by MSzturc** [comment]
That is really strange, can't reproduce this behavior. But the code inside is a bit messy, i will refactor so that you could retest it with the next version

**Comment by MSzturc** [comment]
i've released 0.16.0. May i ask you to retest?

**Comment by wenlzhang** [comment]
With version 0.16.0, the error messages disappeared. However, the internal links are rendered as normal text, with `previewLinks: true` or `previewLinks: false`. This way, I cannot click the note link to going to the note content. Is this the desired behaviour?

**Comment by MSzturc** [comment]
This is exactly how I intended it to behave. In my workflow, I have little or no information in my slides. Everything comes from my vault's notes and is embedded to my slides . My notes link to each other, which is misleading in a presentation, so I switched off the backlinks into the vault first.  I don't think a property approach makes sense because it depends on the Source Material which could be diffrent based on the content you want to use inside your slides.

As workaround have a look at [URI Links](https://mszturc.github.io/obsidian-advanced-slides/basic-syntax/links/) in the documentation

**Comment by wenlzhang** [comment]
Thanks for the detailed explanations!

> Everything comes from my vault's notes and is embedded to my slides.

When embedding notes as list items, their content cannot be shown. Instead, only the note title is rendered, just like note links. For instance, in the following example, `Note A` would behave as desired, while `Note B` would not. Is it possible to fix this?
```
## Slide

![[Note A]]

- ![[Note B]]

```

> My notes link to each other, which is misleading in a presentation, so I switched off the backlinks into the vault first.

I understand that note links can be misleading when showing in slides.

In my workflow, I may use note links in the speaker notes part. This way, I can go into the desired notes when needed, e.g. when answering the audience's questions. While I want to show the link relationship for linked notes like this, using the Obsidian URI approach may not be the ideal way for doing this.

Therefore, is it possible to add some kind of switch for showing note links (such that one can click on it) in the speaker notes part of the slides, e.g. in the following example?
```
## Slide

- Item A
- Item B

note:

- Note A
- Note B
- More details regarding XX can be found in [[Note XX]]
```
Maybe a switch like `previewInternalLinksInNotes: true` can be set in the front matter of slides as a local switch or an option in the configuration page of this plugin as a global switch?

**Comment by MSzturc** [comment]
added enableLinks frontmatter property with 0.17.0

**Comment by wenlzhang** [comment]
Thanks for the update!

With 0.17.0, all note links, including those in the slide content and speaker notes, are rendered as follows and they are not clickable.
```
## Slide

- [Note XX](obsidian://open?vault=Obsidian&file=Note XX)
- Item B

note:

- Note A
- Note B
- More details regarding XX can be found in [Note XX](obsidian://open?vault=Obsidian&file=Note XX)
```

**Comment by MSzturc** [comment]
Well.. guess it's time to start writing unit tests to prevent voodoo effects.

0.17.1 should fix link rendering

**Comment by wenlzhang** [comment]
With the updated version, note links in the content (note the speaker notes part) part of the slide would also be rendered. Is this the desired behaviour?

Also, if the first list item starts with note link, i.e. with no additional text before the note link, then the list items would not render correctly, e.g. in the following example.

```
## Slide

- [[Note XX]] (rendered properly as note links) - [[Note YY]] (rendered properly as note links)
- Item C

note:

- Note A
- Note B
- More details regarding XX can be found in [[Note XX]] (rendered properly as note links)
```

**Comment by MSzturc** [comment]
Well, it wasn't intended, but it makes sense to me.

I've made a couple of bugfixes in 0.17.2, your sample should be rendered correctly on 0.17.2

**Comment by wenlzhang** [comment]
> I've made a couple of bugfixes in 0.17.2, your sample should be rendered correctly on 0.17.2

Great! It works now.

In case you missed it, another issue is that when embedding notes as list items, the content cannot be displayed, e.g. `Note B` in the following example.
```
## Slide

![[Note A]]

- ![[Note B]]
```

**Comment by MSzturc** [comment]
Yes, that's how I imagined it. It is difficult to embed a complete note as a bullet point without destroying the layout. ( I know that obsidian is able to do it but they embed the note as iframe and i render it as part of the slide). I've always managed to avoid it in the past. Therefore i decided to not allow it. Do you have an example where it would make sense?

**Comment by wenlzhang** [comment]
> I know that obsidian is able to do it but they embed the note as iframe and i render it as part of the slide

In fact, this is why I wanted to have this feature in this slides plugin. Sometimes, I may embed notes under/as list items in ordinary Obsidian notes, just to show the hierarchical structure of the note content. Therefore, it would be great if this plugin can also support this feature, then I do not need to change the way of linking/embedding notes when creating slides. Or I can easily convert existing notes as slides. This is mainly for having a consistent workflow. :-)

Also, supporting embedding notes, whether as/under list items or not, in a way similar to iframe would be very helpful when the embedded notes have long relatively long content. For instance, one may want to embed a note whose main content is multiple lines of code snippet.

- In such a case, this code snippet is mainly for the purpose of demonstration. Therefore, it would be great if there can be some kind of box/iframe (I forgot the term for that 😅) of a size that depends on the size of the slide.
- For the remaining content of the note, one can use some kind of slide bar to scroll up and down.
- Another benefit of embedding notes like this is to avoid not being able to show the complete content of the note when the content is relatively long.

Of course, there can be a separate option for choosing whether to render the embedded notes as part of the slides or in a way similar to iframe. Such an option can be configured in the front matter for all slides, or it can be configured on a per slide basis.
