### ISSUE TITLE
can't render slides on side panel

### ISSUE THREAD

**Issue by Rayd62** [MSzturc/obsidian-advanced-slides#80]
Hi MSzturc,

I just installed your plugin from obsidian community, however it seems there is a problem to render the slide.

Once I installed the plugin, the plugin folder looks like:
![](https://cdn.jsdelivr.net/gh/Rayd62/note_images/202205111358431.png)

I created a new note, pasted the content from "first steps" on your document. After that, I click the button "show slide preview", only a white page show on my right panel, nothing else.
![](https://cdn.jsdelivr.net/gh/Rayd62/note_images/202205111400274.png)

I tried "refresh button“ and changed the port in setting. It can't work.

Then I opened Obsidian Developer Console. I found some errors there, it seems I missed some files to work well.
The error show below:
```javascript
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/dingxingyuan/Library/Mobile Documents/iCloud~md~obsidian/Documents/工作台/.obsidian/plugins/obsidian-advanced-slides/template/reveal.html'
await (async)
handle @ VM588:9564
next @ VM588:9730
dispatch @ VM588:9712
handle @ VM588:9564
eval @ VM588:9990
param @ VM588:10035
param @ VM588:10044
process_params @ VM588:10073
next @ VM588:9985
expressInit @ VM588:10239
handle @ VM588:9564
trim_prefix @ VM588:10013
eval @ VM588:9992
process_params @ VM588:10021
next @ VM588:9985
query2 @ VM588:10718
handle @ VM588:9564
trim_prefix @ VM588:10013
eval @ VM588:9992
process_params @ VM588:10021
next @ VM588:9985
handle @ VM588:9923
handle @ VM588:13390
app @ VM588:23949
emit @ node:events:390
parserOnIncoming @ node:_http_server:951
parserOnHeadersComplete @ node:_http_common:128
```
```javascript
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3100') does not match the recipient window's origin ('app://obsidian.md').
```

Reinstall can't help me to solve the problem, so I wonder if there any library or something I need to install before using your awesome plugin?

**Comment by Rayd62** [comment]
By the way, My environment is Apple M1 Macbook Air, OS version is 12.3.1.
The obsidian version is v0.14.6
The advanced slides plugin version displays 1.6.0
Thanks!

**Comment by MSzturc** [comment]
Please have a look at #63

**Comment by Rayd62** [comment]
Thanks for your help, it was my proxy on Mac that caused the problem.
