### ISSUE TITLE
Performance issue with `onMessage` handler

### ISSUE THREAD

**Issue by rxian** [MSzturc/obsidian-advanced-slides#83]
https://github.com/MSzturc/obsidian-advanced-slides/blob/1e71dc36c08f5d7b10a0c527b0f26e36a0bdc6a5/src/revealPreviewView.ts#L33

https://github.com/MSzturc/obsidian-advanced-slides/blob/1e71dc36c08f5d7b10a0c527b0f26e36a0bdc6a5/src/revealPreviewView.ts#L60-L78

I was doing a presentation last week and encountered some serious performance issues when navigating between slides. When I measure the performance, it seems that a significant proportion of runtime is spent on the `onMessage` function call. Could the performance of this subroutine be improved? It seems that this event is fired whenever I switch slides. Thanks!

**Comment by MSzturc** [comment]
That's weird. The only thing that onMessage does is to synchronize the current line with the slide you are viewing. The operations are mostly trivial, i've done some performance measurement with chrome dev tools an my response time where all < 1ms with a deck of 60 slides an ~1500 loc markdown in source file.

Can you reproduce this issue?

**Comment by rxian** [comment]
Yea sorry, actually ignore this for now, I guess my issue might be that my Obsidian is overloaded with plugins...
