### ISSUE TITLE
backtick ` to escape Latex not working 

### ISSUE THREAD

**Issue by rleyvasal** [MSzturc/obsidian-advanced-slides#84]
The use of backtick to escape Latex code is not working in markdown

**Code to replicate**

```
-   enclosed in `$ $`  such as  `$\sigma$` get $\sigma$
````

Current output

![output latex](https://user-images.githubusercontent.com/61335136/168324795-22d6acc9-a185-4c1d-a68e-caa591d19df2.PNG)

Expected output

![expected latex](https://user-images.githubusercontent.com/61335136/168132600-9ebcad09-f727-4f9d-8b5b-f2b07111e41b.PNG)

**Comment by MSzturc** [comment]
This is not a bug, it's an feature ;-)

Have a look here: https://stackoverflow.com/questions/62111699/mathjax-strangely-render-back-tick-in-code-blocks

**Comment by rleyvasal** [comment]
I read it but I still cannot figure out how to comment out $\sigma$

**Comment by MSzturc** [comment]
Its not possible since backticks are reserved for math operations what you could do is to escape the dollar symbol

```
inline \\$\sigma\\$ latex with ==\\$\sigma\\$==
```

**Comment by rleyvasal** [comment]
Thanks @MSzturc !
