### ISSUE TITLE
Short cut for elements, e.g. {.fragment}

### ISSUE THREAD

**Issue by rleyvasal** [MSzturc/obsidian-advanced-slides#85]
Is it possible to provide shortcuts for elements such as `{.fragment}` instead of `<!-- element class="fragment" -->`

This link contains some examples, [quarto examples](https://tutorial.quarto.org/docs/presentations/revealjs/advanced.html#fragments)

it can also be used for styling such as `{data-id="box1" style="background: #2780e3; width: 350px; height: 350px; border-radius: 200px;"}` or `{.fragment .grow}`

**Comment by MSzturc** [comment]
When i designed advanced slides i decided not to implement the shortcode syntax since it will be display in the obsidian render which was a flaw in my point of view.

Since 1.10 we have auto suggest for the syntax so it's even shorter that your example:

```
el<return>fr<return>1
```
and you get 

```
<!-- element frag="1" -->
```

**Comment by rleyvasal** [comment]
Got it thanks for your work in this project!
