### ISSUE TITLE
Browser mode / PDF export cannot find images

### ISSUE THREAD

**Issue by fedeadolfi** [MSzturc/obsidian-advanced-slides#86]
When opening in browser or exporting to PDF, images are not rendered, presumably because paths are not correct (although they work in Slide Preview in Obsidian). Images are in a folder which is in the same directory the slides are in, all of which is in the Obsidian vault.

Would this be an issue with the root of the local server that is launched when clicking "Open in Browser"?

**Comment by MSzturc** [comment]
Im not able to reproduce this issue, can you provide me a sample vault?

**Comment by fedeadolfi** [comment]
I just solved it. My vault was in iCloudDrive. Moving it to my local project folder solved the issue.

**Comment by MSzturc** [comment]
Had this problem with my gdrive too. Had to disable "smart" synchronization since it created a filesystem based on symlinks that could be resolved.
