### ISSUE TITLE
[Feature] Support default backgroud image

### ISSUE THREAD

**Issue by lijin305** [MSzturc/obsidian-advanced-slides#93]
According to the [documentation](https://mszturc.github.io/obsidian-advanced-slides/extend-syntax/slidebackground/), it seems need to add code to set the background `<bg>` for each slide.

Is it possible to support a default background image for all slides? (When individual pages need special background images, they can be overridden using the current `<bg>` command)

The [parallaxBackgroundImage](https://revealjs.com/backgrounds/#parallax-background) parameter of [Realjs](https://revealjs.com/) can achieve similar functionality, but it doesn't seem to be supported at the moment.

**Comment by MSzturc** [comment]
implemented in 1.14
