### ISSUE TITLE
cannot be opened the outer chain in the rendered page 

### ISSUE THREAD

**Issue by Doslin** [MSzturc/obsidian-advanced-slides#94]
Blocked opening 'obsidian://open?vault=doude&file=get%20things%20done/pandora_%E5%AE%9E%E9%AA%8C%E6%8A%A5%E5%91%8A%E5%AD%98%E6%A1%A3%E8%AE%BE%E8%AE%A1_22-02-07_Mon.md' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.

![image](https://user-images.githubusercontent.com/29807388/173193479-65e11548-3613-4287-961f-2f798c902746.png)

**Comment by MSzturc** [comment]
fixed in 1.14.4
