### ISSUE TITLE
Footnote style not getting applied to the list element numeral

### ISSUE THREAD

**Issue by pandichef** [MSzturc/obsidian-advanced-slides#97]
e.g.,
`[^1]: see Thinking Fast and Slow <!-- element class="footnotes" style="font-size: 20px " -->`

"see Thinking Fast and Slow" is now 20px, but the "1." is still the original size

**Comment by MSzturc** [comment]
With the next version of advanced slides every footnote item will have a footnote class that could be used for styling like this:

    <style>
    .footnote {
	    font-size: 20px;
    }
    </style>
