### ISSUE TITLE
slide preview error when md file is within a subfolder of the obsidian library

### ISSUE THREAD

**Issue by Liampor** [MSzturc/obsidian-advanced-slides#98]
Hello,

I have trouble using this nice extension.

Given that my `test.md` file contains the code below
`<!-- slide: data-background-iframe="https://www.google.com" data-background-interactive-->`

If I put the file in the root of the obsidian library, all works fine.

Once I put the md file in a subfolder like `00_Test`, It returns error in the console:

> plugin:obsidian-advanced-slides:299 Uncaught (in promise) Error: ENOENT: no such file or directory, open '<lib_root>\00_Test%2Ftest.md'

It seems the strange "**%2F**" causes this problem.

------------------------
Advanced Slides Version: 1.14.1
Obsidian V0.14.15
System: Windows 10 & macOS 15

**Comment by MSzturc** [comment]
Yeah that's a problem with a fix thats not work as expected. I rolled back the fix with 1.14.2 and will create a more robust approach in 1.14.3

**Comment by MSzturc** [comment]
please retest with 1.14.3

**Comment by Liampor** [comment]
> 

It works well now. Thank you so much for the quick response!
