### ISSUE TITLE
Slide Preview Disappeared when upgrading to Version 1.14.1 from Version 1.14.0

### ISSUE THREAD

**Issue by TimothyGutierrez** [MSzturc/obsidian-advanced-slides#99]
Was using Version 1.14.0. Everything worked fine. Upgraded plugin to 1.14.1. No other changes to Obsidian. Now, no slide preview. Just a blank screen where the presentation preview should be.

**Comment by TimothyGutierrez** [comment]
Thank you very much for your prompt response. 
/Users/timothy/Library/Mobile Documents/iCloud~md~obsidian/Documents/Jenks-2022-02-25_template_starter_vault/presentations/TestPresentation.md
I'm not sure what info if useful in error checking. I'll provide whatever info assists in solving this problem.

**Comment by MSzturc** [comment]
please retest with 1.14.3

**Comment by TimothyGutierrez** [comment]
Upgrading to 1.14.3 appears to have resolved the issue. Thank you.
